Repository kitravee/febfeb, pull requests merged in 2022-05, with the labels that each got.

#3 Feature/auth and cms
  .eslintrc
  .github/workflows/ci.yml
  package.json
  src/hooks/useAnchorElement.ts
  src/hooks/useDisclosure.ts
  src/layouts/main-layout/responsive-main-appbar/index.tsx
  src/lib/graphql.ts
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  theme/theme-colors.ts
  theme/theme.ts
  yarn.lock
Labels: enhancement

#9 Feature/add google button#8
  src/layouts/main-layout/responsive-main-appbar/index.tsx
Labels: enhancement

#11 10 Link Account Feature
  .eslintrc
  next.config.js
  package.json
  src/config/environment.ts
  src/config/index.ts
  src/lib/axios.ts
  src/lib/graphql.ts
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/auth/link-gql-account.ts
  src/pages/api/auth/next-auth.d.ts
  src/utils/axios.ts
  src/utils/env.ts
  theme/mui.d.ts
  yarn.lock
Labels: enhancement, rfr

#14 12 footer team contact
  package.json
  public/home/crypto-hero.png
  public/home/undraw_explore_re_8l4v.svg
  src/components/link.tsx
  src/components/router-link.tsx
  src/components/text-gradient.tsx
  src/layouts/main-layout/footer.tsx
  src/layouts/main-layout/responsive-main-appbar/index.tsx
  src/views/home-view/hero.tsx
  src/views/home-view/index.tsx
  theme/theme-colors.ts
  theme/theme.ts
  yarn.lock
Labels: rfr
